#!/bin/bash
mount c:/mingw /mingw 2> /dev/null
set -e

if [ -z "$1" ]; then
  echo "Usage: $0 package-name"
  exit 1
fi

export WINBOX_SCRIPTS=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
export WINBOX="$(pwd)/.winbox/"
if [ ! -d "$WINBOX" ]; then
  echo "No Winbox found. Try wb-init first"
  exit 1
fi
mkdir -p "$WINBOX/download/"
export CPPFLAGS="-I$WINBOX/include $CPPFLAGS"
export LDFLAGS="-L$WINBOX/lib $LDFLAGS"
export PATH="$WINBOX/bin:$PATH"
export ACLOCAL_PATH="$WINBOX/share/aclocal:$ACLOCAL_PATH"
export PKG_CONFIG_PATH="$WINBOX/lib/pkgconfig:$PKG_CONFIG_PATH"
"$WINBOX_SCRIPTS/installers/$1"
