#!/bin/bash
set -e

if [ -f "$WB/lib/libfftw3.a" ]; then
  exit 0
fi

mingw-get install msys-wget mingw32-gcc mingw32-gcc-fortran

cd "$WB/download"
wget -O fftw-3.3.4.tar.gz "http://www.fftw.org/fftw-3.3.4.tar.gz"
tar -xvzf fftw-3.3.4.tar.gz
cd fftw-3.3.4
./configure --prefix="$WB"
make
make install
