#!/bin/bash
set -e

if [ -f "$WB/bin/libFLAC-8.dll" ]; then
  exit 0
fi

"$WINBOX_BIN" install libogg

mingw-get install msys-wget mingw32-gcc mingw32-gcc-g++

cd "$WB/download"
wget -O flac-1.3.1.tar.xz "http://downloads.xiph.org/releases/flac/flac-1.3.1.tar.xz"
tar -xf flac-1.3.1.tar.xz
cd flac-1.3.1
./configure --prefix="$WB"
make
make install
