#!/bin/bash
set -e

if [ -f .winbox/bin/libogg-0.dll ]; then
  exit 0
fi

mingw-get install msys-wget

wget -O "$WINBOX/download/libogg-1.3.2.tar.gz" "http://downloads.xiph.org/releases/ogg/libogg-1.3.2.tar.gz"
tar -C "$WINBOX/download" -xvzf "$WINBOX/download/libogg-1.3.2.tar.gz"
cd "$WINBOX/download/libogg-1.3.2"
./configure --prefix="$WINBOX"
make
make install
