#!/bin/bash
set -e

if [ -f "$WB/bin/libogg-0.dll" ]; then
  exit 0
fi

mingw-get install msys-wget mingw32-gcc

cd "$WB/download"
wget -O libogg-1.3.2.tar.gz "http://downloads.xiph.org/releases/ogg/libogg-1.3.2.tar.gz"
tar -xvzf libogg-1.3.2.tar.gz
cd libogg-1.3.2
./configure --prefix="$WB"
make
make install
