#!/bin/bash
set -e

if [ -f "$WB/bin/libsndfile-1.dll" ]; then
  exit 0
fi

"$WINBOX_BIN" install python
"$WINBOX_BIN" install pkg-config
"$WINBOX_BIN" install libogg libvorbis libflac

mingw-get install mingw32-gcc mingw32-autotools msys-autogen

cd "$WB/download"
if [ -d libsndfile ]; then
  cd libsndfile
  git pull
else
  git clone https://github.com/erikd/libsndfile
  cd libsndfile
fi
./autogen.sh
./configure --prefix="$WB"
make
make install
