#!/bin/bash
set -e

if [ -f "$WB/bin/libvorbis-0.dll" ]; then
  exit 0
fi

"$WINBOX_BIN" install libogg

mingw-get install msys-wget mingw32-gcc

cd "$WB/download"
wget -O libvorbis-1.3.5.tar.gz "http://downloads.xiph.org/releases/vorbis/libvorbis-1.3.5.tar.gz"
tar -xvzf libvorbis-1.3.5.tar.gz
cd libvorbis-1.3.5
./configure --prefix="$WB"
make
make install
