#!/bin/bash
set -e

if [ -f .winbox/bin/pkg-config.exe ]; then
  exit 0
fi

mingw-get install msys-wget msys-unzip

cd "$WB/download"
wget -O pkg-config_0.26-1_win32.zip "http://ftp.gnome.org/pub/gnome/binaries/win32/dependencies/pkg-config_0.26-1_win32.zip"
wget -O glib_2.28.8-1_win32.zip "http://ftp.gnome.org/pub/gnome/binaries/win32/glib/2.28/glib_2.28.8-1_win32.zip"
wget -O gettext-runtime_0.18.1.1-2_win32.zip "http://ftp.gnome.org/pub/gnome/binaries/win32/dependencies/gettext-runtime_0.18.1.1-2_win32.zip"
wget -O pkg-config-dev_0.26-1_win32.zip "http://ftp.gnome.org/pub/gnome/binaries/win32/dependencies/pkg-config-dev_0.26-1_win32.zip"
unzip pkg-config_0.26-1_win32.zip -d "$WB"
unzip glib_2.28.8-1_win32.zip -d "$WB"
unzip gettext-runtime_0.18.1.1-2_win32.zip -d "$WB"
unzip pkg-config-dev_0.26-1_win32.zip -d "$WB"

# needed for libsndfile?
mkdir -p /mingw/share/aclocal/
cp "$WB/share/aclocal/pkg.m4" /mingw/share/aclocal/
