#!/bin/bash
set -e

if [ -f "$WB/bin/pthreadVC2.dll" ]; then
  exit 0
fi

mingw-get install msys-wget msys-unzip

cd "$WB/download"
wget -O pthreads-w32-2-9-1-release.zip "ftp://sourceware.org/pub/pthreads-win32/pthreads-w32-2-9-1-release.zip"
unzip -o pthreads-w32-2-9-1-release.zip
cp -R Pre-built.2/dll/x86/* "$WB/bin/"
cp -R Pre-built.2/include/* "$WB/include/"
cp -R Pre-built.2/lib/x86/* "$WB/lib/"
cp "$WB/lib/libpthreadGC2.a" "$WB/lib/libpthread.a"
