#!/bin/bash
set -e

if [ -f "$WB/lib/libvamp-sdk.a" ]; then
  exit 0
fi

"$WINBOX_BIN" install libsndfile

mingw-get install msys-wget mingw32-gcc mingw32-gcc-g++

cd "$WB/download"
wget -O vamp-plugin-sdk-2.5.tar.gz "http://code.soundsoftware.ac.uk/attachments/download/690/vamp-plugin-sdk-2.5.tar.gz" --no-check-certificate
tar -xvzf vamp-plugin-sdk-2.5.tar.gz
cd vamp-plugin-sdk-2.5
./configure --prefix="$WB"
make
make install
